services:
  jenkins:
    image: jenkins-cutom:latest
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_PATH}:/usr/bin/docker

volumes:
  jenkins-home:
